hydra:
  run:
    dir: .
  output_subdir: null
  
data:
  filepath: '/media/data/student/paxraypp/paxray_train_val.json'
  # filepath: 'batch_test.json'
  image_dir: '/media/data/student/paxraypp/paxray_images_unfiltered/images_patlas'
  labels_dir: '/media/data/student/paxraypp/labels_unpacked/labels_converted'
  batch_size: 10

train:
  model_dir: 'models_checkpoint'
  lr: 0.0003
  num_classes: 27
  decay: 0.2
  moving_avg_alpha: 0.1
  patience: 30
  valid_cutoff: 60
  train_threshold: 0.005
  valid_threshold: 0.005
  total_epochs: 200
  epoch_length: 250
  save_every: 100
  load_state: False
  

