hydra:
  run:
    dir: .
  output_subdir: null
  
data:
  filepath: '/media/data/student/paxraypp/paxray_train_val.json'
  # filepath: 'batch_test.json'
  image_dir: '/media/data/student/paxraypp/paxray_images_unfiltered/images_patlas'
  labels_dir: '/media/data/student/paxraypp/labels_unpacked/labels_converted'
  batch_size: 4
  channels: [2, 3, 4, 5, 6, 15] # lung_lower_lobe_left, lung_upper_lobe_left, lung_lower_lobe_right, lung_middle_lobe_right, lung_upper_lobe_right, heart

train:
  model_dir: 'models_checkpoint'
  lr: 0.000012
  num_classes: 16
  decay: 0.2
  moving_avg_alpha: 0.1
  patience: 10
  valid_cutoff: 20
  train_threshold: 0.005
  valid_threshold: 0.005
  total_epochs: 500
  epoch_length: 800
  valid_epoch_length: 100
  save_every: 25
  load_state: # Leave empty if not loading from checkpoint
  
run:
  num_classes: 7
  weights: 'weights/lungs-heart-weights.pt'
