lung_heart_weights: 'weights/lung-heart-weights.pt'
bones_weights: 'weights/bones-weights.pt'
output_folder: 'outputs'
input_image: 'image_00000copy.png'
label_image: '/media/data/student/paxraypp/labels_unpacked/labels_converted/RibFrac_056_frontal.npy' # Leave empty if none
